export default [
  {
    id: 5,
    category_id: 1,
    product_name: "Undetectable Mouse Jiggler",
    product_details:
      "You'd pay $24 at Amazon, Buy Now at Woot! An Amazon Company",
    price: "24",
    image: `/images/mouse_jiggler.jpg`,
    off_percent: "41",
    no_products: 20,
    created_at: "2023-07-19T14:10:04.000Z",
    rating: 5,
    staff_pick: "",
    key_words: "Mac,Popularity 5/5",
    supplier: "amazon",
    tip: "",
    features: "",
    code: "",
    breadcrumbs: "All deals, Mice/Trackballs, Woot! An Amazon Company",
    category: "electronics",
  },
  {
    id: 6,
    category_id: 2,
    product_name: "Rheem AC / Furnace Pleated Air Filter 12-Pack",
    product_details: "That's just $1.66 per filter, Buy Now at Home Depot",
    price: "20",
    image: "/images/rheem_ac.jpg",
    off_percent: "0",
    no_products: 14,
    created_at: "2023-07-19T14:10:04.000Z",
    rating: 5,
    staff_pick: "",
    key_words: "Under $25,Popularity 5/5",
    supplier: "home depot",
    tip: "",
    features: 'each measures 10" x 24" x 1"',
    code: "",
    breadcrumbs: "All Deals,Home & Garden,Home Depot",
    category: "home & garden",
  },
  {
    id: 7,
    category_id: 3,
    product_name: "Vineyard Vines Men's Sale",
    product_details:
      'Use code "SALE50" to get an extra 50% off already discounted styles, Shop Now at Vineyard Vines',
    price: "89",
    image: "/images/vineyard_vines_men_shirt.jpg",
    off_percent: "55",
    no_products: 40,
    created_at: "2023-07-19T15:57:24.000Z",
    rating: 5,
    staff_pick: "",
    key_words: "Men's, Popularity: 5/5",
    supplier: "Vineyard Vines",
    tip: "",
    features:
      "Pictured is the Vineyard Vines Men's Surfside Pique Polo for $31 after code ($58 off).",
    code: "SALE50",
    breadcrumbs: "All Deals,Clothing & Accessories,Vineyard Vines",
    category: "clothing & accessories",
  },
  {
    id: 8,
    category_id: 1,
    product_name: "Apple Brand iPhone Accessories at Amazon",
    product_details:
      "Save on a selection of about four dozen items, Shop Now at Amazon",
    price: "40",
    image: "/images/magsafe_charger.jpg",
    off_percent: "20",
    no_products: 12,
    created_at: "2023-07-19T15:57:24.000Z",
    rating: 5,
    staff_pick: "Deals so good we bought one ourselves",
    key_words:
      "iOS,Amazon Prime Day, Aniversarry Event,Staff Pick,Mac,Popularity: 5/5",
    supplier: "amazon",
    tip: "",
    features: "Apple Magsafe Charger pictured for $31 ($8 off).",
    code: "",
    breadcrumbs: "All Deals,iPhone Accessories,Amazon",
    category: "electronics",
  },
  {
    id: 9,
    category_id: 1,
    product_name: "1080p RC Quadcopter Drone",
    product_details:
      'Apply coupon code "80S9TIAU" and get the 10% off checkout discount to save $360, Buy Now at Amazon',
    price: "400",
    image: "/images/amazon_drone.jpg",
    off_percent: "80",
    no_products: 10,
    created_at: "2023-07-19T16:09:01.000Z",
    rating: 5,
    staff_pick: "",
    key_words: "Popularity: 5/5",
    supplier: "amazon",
    tip: "",
    features:
      "trajectory flight,altitude hold,3-level flight speed,LED lights,includes two batteries",
    code: "80S9TIAU",
    breadcrumbs: "All Deals,Drones,Amazon",
    category: "electronics",
  },
  {
    id: 10,
    category_id: 3,
    product_name: "Quiksilver Pierside Lifeguard Beach Sun Straw Hat",
    product_details: "You'd pay $10 more elsewhere, Buy Now at Amazon",
    price: "22",
    image: "/images/amazon-hat.jpg",
    off_percent: "46",
    no_products: 43,
    created_at: "2023-07-19T16:09:01.000Z",
    rating: 5,
    staff_pick: "",
    key_words: "Amazon Prime Day, Aniversary Event,Under $25, Popularity: 5/5",
    supplier: "amazon",
    tip: "",
    features: "",
    code: "",
    breadcrumbs: "All Deals,amazon,Clothing & Accessories",
    category: "clothing & accessories",
  },
  {
    id: 11,
    category_id: 2,
    product_name: '17.5" x 78.7" One Way House Privacy Film',
    product_details:
      'Get a total savings of $9 with code "745Y8POO", Buy Now at Amazon',
    price: "15",
    image: "/images/house_privacy.jpg",
    off_percent: "30",
    no_products: 13,
    created_at: "2023-07-19T16:18:17.000Z",
    rating: 5,
    staff_pick: "",
    key_words: "Popularity: 5/5",
    supplier: "amazon",
    tip: "",
    features: "static film,blocks infrared and up to 91% of UV rays",
    code: "745Y8POO",
    breadcrumbs: "All Deals,Decor,Amazon",
    category: "home & garden",
  },
  {
    id: 12,
    category_id: 2,
    product_name: '36" Silicone Mat for Blackstone Griddle',
    product_details:
      'Clip the $2 off on page coupon and apply coupon code "40FEG39B" to get the best price we could find by $29, Buy Now at Amazon',
    price: "38",
    image: "/images/amazon_griddle.jpg",
    off_percent: "50",
    no_products: 32,
    created_at: "2023-07-19T16:18:17.000Z",
    rating: 4,
    staff_pick: "",
    key_words: "Popularity: 4/5",
    supplier: "amazon",
    tip: "",
    features: "heavy duty,100% food-grade silicone,Model: MF99173",
    code: "40FEG39B",
    breadcrumbs: "All Deals,Home & Garden,Amazon",
    category: "home & garden",
  },
  {
    id: 13,
    category_id: 3,
    product_name: "Philips GoZero 22-oz. Everyday Filtered Water Bottle",
    product_details: "That's a low by $6, Buy Now at Amazon",
    price: "17",
    image: "/images/water_bottel.jpg",
    off_percent: "0",
    no_products: 14,
    created_at: "2023-07-19T16:27:30.000Z",
    rating: 3,
    staff_pick: "",
    key_words: "Back to School, Under $25, Popularity: 3/5",
    supplier: "amazon",
    tip: "",
    features:
      "activated carbon fiber,built-in carry loop,pop-up lid,BPA-free,Model: AWP2731BLO/37",
    code: "",
    breadcrumbs: "All Deals,Kitchen,Amazon,Philips",
    category: "clothing & accessories",
  },
  {
    id: 14,
    category_id: 3,
    product_name: "Gap Factory Men's 5\" Boxer Briefs 3-Pack",
    product_details:
      'Add them to your cart and apply coupon code "GFSHIP" to make for a total savings of $38,Buy Now at Gap Factory\r\n\r\n',
    price: "37",
    image: "/images/underwear.jpg",
    off_percent: "80",
    no_products: 21,
    created_at: "2023-07-19T16:27:30.000Z",
    rating: 4,
    staff_pick: "",
    key_words: "Men's,Staff Pick,Under $25,Popularity: 4/5,Under $10",
    supplier: "gap factory",
    tip: "",
    features: "pictured in Warm Multi",
    code: "GFSHIP",
    breadcrumbs: "All Deals,Under wear,Gap Factory",
    category: "clothing & accessories",
  },
  {
    id: 15,
    category_id: 2,
    product_name: 'Legend Force 20" Gas Rear Tine Tiller',
    product_details:
      "That's a savings of more than 70% off,Buy Now at Home Depot",
    price: "699",
    image: "/images/rear_tine_tiller.jpg",
    off_percent: "80",
    no_products: 43,
    created_at: "2023-07-19T16:37:21.000Z",
    rating: 4,
    staff_pick: "",
    key_words: "Popularity: 4/5",
    supplier: "home depot",
    tip: "",
    features:
      "self-propelled,pneumatic wheels,212cc OHV gas-powered engine,adjustable forward speed with 4 tines,Model: LF20212RTG",
    code: "",
    breadcrumbs: "All Deals,Outdoor Power Equipment, Home Depot",
    category: "home & garden",
  },
  {
    id: 16,
    category_id: 1,
    product_name: "100W USB-C Laptop Charger",
    product_details:
      'Clip the 15% off on page coupon and apply coupon code "ZVEPKEWW" to save $19,Buy Now at Amazon',
    price: "29",
    image: "/images/laptop_charger.jpg",
    off_percent: "50",
    no_products: 12,
    created_at: "2023-07-19T16:37:21.000Z",
    rating: 4,
    staff_pick: "",
    key_words: "Popularity: 4/5",
    supplier: "amazon",
    tip: "",
    features: "7.2-foot USB-C cable,Model: ZB-A1496",
    code: "ZVEPKEWW",
    breadcrumbs: "All Deals,Laptop Accessories,Amazon",
    category: "electronics",
  },
];
